from page_objects.Checkout_Page_Objects import CheckoutPage
from page_objects.Home_Page_Objects import HomePage
from page_objects.Login_Page_Objects import LoginPage
from page_objects.Product_Page import ProductPage
from page_objects.Woment_TAB_Page_Object import WomenTitlePage
from utilities.readProperties import readConf


class TestE2EScenarios:
    def test_ordering_a_small_size_tshirt(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product1_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_tshirt(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product1_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_tshirt(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product1_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_small_size_blouse(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product2_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_blouse(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product2_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_blouse(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product2_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_small_size_printed_dress1(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product3_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_printed_dress1(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product3_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_printed_dress1(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product3_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_small_size_printed_dress2(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product4_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_printed_dress2(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product4_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_printed_dress2(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product4_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_small_size_printed_summer_dress1(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product5_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_printed_summer_dress1(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product5_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_printed_summer_dress1(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product5_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_small_size_printed_summer_dress2(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product6_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_printed_summer_dress2(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product6_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_printed_summer_dress2(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product6_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_small_size_printed__chiffon_dress(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product7_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_small_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_medium_size_printed_chiffon_dress(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product7_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_medium_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()

    def test_ordering_a_large_size_printed_chiffon_dress(self, setup_method):
        self.driver = setup_method
        self.homepage = HomePage(self.driver)
        assert self.driver.title == readConf.get_home_page_title()
        for i in range(1):
            self.homepage.click_on_signin_link()
            assert self.driver.title == readConf.get_login_page_title()
            self.loginpage = LoginPage(self.driver)
            self.loginpage.enter_existing_user_email(readConf.get_useremail())
            self.loginpage.enter_existing_user_password(readConf.get_userpassword())
            self.loginpage.click_login_button()
            assert self.driver.title == readConf.get_my_account_page_title()
            self.homepage.click_on_women_tab()
            self.womenpage = WomenTitlePage(self.driver)
            self.womenpage.click_on_list_view()
            self.womenpage.click_on_specified_product(readConf.get_product7_text())
            self.productpage = ProductPage(self.driver)
            self.productpage.select_size(readConf.get_large_size())
            self.productpage.add_to_cart()
            self.productpage.verify_product_added_to_cart()
            self.productpage.click_on_proceed_to_checkout_button()
            self.checkoutpage = CheckoutPage(self.driver)
            assert self.driver.title == readConf.get_checkout_page_title()
            self.checkoutpage.click_on_proceed_to_address_step()
            self.checkoutpage.click_on_proceed_to_shipping_step()
            self.checkoutpage.click_to_agree_terms_on_shipping_step()
            self.checkoutpage.click_on_proceed_to_payment_step()
            self.checkoutpage.click_on_pay_by_bank_wire_link()
            self.checkoutpage.click_on_order_confirm_button()
            assert self.driver.title == readConf.get_order_confirmation_page_title()
            self.loginpage.click_logout_button()
        self.driver.quit()
